apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: db-init
  name: db-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-init
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker/docker-compose.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: db-init
    spec:
      containers:
        - args:
            - database
            - init
            - -config
            - /boundary/boundary.hcl
          env:
            - name: BOUNDARY_PG_URL
              value: postgresql://user_boundary:x0QMsakg7vdl@ep-late-flower-943698.ap-southeast-1.aws.neon.tech/tools_boundary?sslmode=require
          image: hashicorp/boundary:0.15.3
          name: db-init
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /boundary
              name: db-init-claim0
      restartPolicy: Always
      volumes:
        - name: db-init-claim0
          persistentVolumeClaim:
            claimName: db-init-claim0
