apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boundary

resources:
- "boundary-claim0-persistentvolumeclaim.yaml"
- "boundary-deployment.yaml"
- "boundary-service.yaml"
- "db-init-claim0-persistentvolumeclaim.yaml"
- "db-init-deployment.yaml"
- "wait-deployment.yaml"

