apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: wait
  name: wait
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wait
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker/docker-compose.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: wait
    spec:
      containers:
        - args:
            - sleep
            - "1"
          image: busybox:latest
          name: wait
      restartPolicy: Always
